### PR TITLE
Add YK 2014; modify the script to account for new package naming patt…

### PR DESCRIPTION
**Pull request by sershe**
Add YK 2014; modify the script to account for new package naming pattern, as well as new structure on mac.

There's no longer an X.Y.Z version pattern, so I am making it out of build #. Looks like first two digits of the build number are the year (this holds for 2013, 2014 and 2015 downloads), so I am using this as a major version.

### CODE REVIEW

**Comment by nitay** [comment]
Good stuff, thanks!

**Comment by sershe** [comment]
Thanks! I tried to push this to sonatype but I don't appear to have access. Can you please release the jars? I guess they'll need to be re-signed too then.

**Comment by nitay** [comment]
Here you go: http://bit.ly/1bVPrYz

**Comment by sershe** [comment]
Thanks!

**Pull request merged**
